baseURL: https://love.devok.store/
languageCode: en-us
title: Love2Love
paginate: 5
theme: "PaperMod"

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
# googleAnalytics: UA-123-45

minify:
    disableXML: true
    # minifyOutput: true

menu:
  main:
    - identifier: search
      name: search
      url: /search/
      weight: 10
    - identifier: categories
      name: categories
      url: /categories/
      weight: 20
    - identifier: tags
      name: tags
      url: /tags/
      weight: 30

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

params:
  env: production
  description: "Love2BeLoved"
  author: George A.
  keywords: [blog, feelings, writeouts]
  categories: 
    - self expression  
  # author: ["Me", "You"] # multiple authors

  defaultTheme: auto
  # disableThemeToggle: true
  ShowShareButtons: true
  ShowReadingTime: false
  # disableSpecial1stPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowToc: true
  #TocOpen: true
  # comments: false
  
  homeInfoParams:
      Title: "Welcome to my blog!"
      Content: >
        I started this blog as an excuse to try out Cloudflare Pages and a 
        place to capture my notes and thoughts on recent events in my life.
        I feel like I had enough containing all my thoughts and all I feel within, so it's time to write it down.
        Again, welcome to my thoughts diary, let's get into it!
  
  socialIcons:
        - name: github
          url: "https://github.com/darxreborn"
        #- name: KoFi
        #  url: "https://ko-fi.com/adityatelange"
        #- name: Rss
          url: "index.xml"

  assets:
    disableFingerprinting: true
    disableHLJS: true

  fuseOpts:
    isCaseSensitive: false
    shouldSort: false
    location: 0
    distance: 0
    threshold: 0.2
    minMatchCharLength: 2
    keys: ["title", "permalink", "summary", "content"]

markup:
  highlight:
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    noClasses: false
    # style: monokai

privacy:
  disqus:
    disable: true
  googleAnalytics:
    anonymizeIP: true
    disable: true
    respectDoNotTrack: true
    useSessionStorage: true
  instagram:
    disable: true
    simple: true
  twitter:
    disable: true
    enableDNT: true
    simple: true
  vimeo:
    disable: true
    enableDNT: true
    simple: true
  youtube:
    disable: true
    privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
